### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by selient** [jedwards1211/async-child-process#16]
do we support child_process fork?

```js
const cp = require('child_process');
const child = await join(cp.fork('some kid'));
```

**Comment by jedwards1211** [comment]
it certainly should, `fork` returns a child process just like `spawn` and `exec`.  If `join` doesn't work with `fork`, please file a bug report.
You may also be interested in my (`promisify-child-process` package)[https://github.com/jcoreio/promisify-child-process] which has a slightly different API and an explicitly tested `fork` wrapper method.

**Comment by jedwards1211** [comment]
Were you satisfied with my answer?  I'm going to go ahead and close this but feel free to continue discussing here if you have any more questions.
